name: Lint

on: 
  - push
  - pull_request

jobs:
  lint:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          runs:
            using: 'node16'
            main: 'main.js'
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src"
          jupyter: true
          version: "~= 22.0"